server:
  tomcat.uri-encoding: UTF-8
  port: 8182

spring:
  application:
      name: smallsix
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306?useUnicode=true&characterEncoding=utf8
      username: root
      password: root
      initialize: true

# Single file max size
multipart.maxFileSize: 100Mb
# All files max size
multipart.maxRequestSize: 1000Mb

mybatis:
  mapper-locations: classpath*:mappers/*
  configuration:
      mapUnderscoreToCamelCase: true

smallsix:
  mysql:
    scan.package: cn.hellosix
    # 配置成跟 jdbc 连接的信息一样
    database.name: smallsix
    # 自动生成前端 js
  user.api.path: ./src/main/resources/public/core/
  userapi.scan.package: cn.hellosix.controller
