server:
  tomcat.uri-encoding: UTF-8
  port: 8182

spring:
  application:
      name: smallsix
  http:
        encoding:
          enabled: true
          force: true
          charset: UTF-8
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306?autoReconnect=true&;failOverReadOnly=false
      username: root
      password: root
      initialize: true

# Single file max size
multipart.maxFileSize: 100Mb
# All files max size
multipart.maxRequestSize: 1000Mb

mybatis:
  mapper-locations: classpath*:mappers/*
  configuration:
      mapUnderscoreToCamelCase: true

smallsix:
  mysql:
    scan.package: cn.hellosix
    # 配置成跟 jdbc 连接的信息一样
    database.name: smallsix
    database.prex: smallsix_
    # 自动生成前端 js
  user.api: http://127.0.0.1:8182/super/api/restful/
  user.api.path: ./src/main/resources/public/core/
  userapi.scan.package: cn.hellosix.controller
  package.path.tmp: /Users/lzz/work/smallsix/src/main/resources/public/package/tmp/
  package.path.pack: /Users/lzz/work/smallsix/src/main/resources/public/package/pack/


logging:
  level:
     cn.hellosix.dao : debug