CREATE DATABASE IF NOT EXISTS smurf7 DEFAULT CHARSET utf8mb4 COLLATE utf8mb4_unicode_ci

CREATE TABLE bannner (
  id int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  image varchar(100) DEFAULT NULL,
  intro VARCHAR(255) DEFAULT NULL,
  index tinyint(2) DEFAULT NULL,
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4;

CREATE TABLE guita (
  id int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  image varchar(100) DEFAULT NULL,
  title VARCHAR (100) DEFAULT NULL,
  intro VARCHAR(255) DEFAULT NULL,
  index tinyint(2) DEFAULT NULL,
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4;

CREATE TABLE music (
  id int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  music_file varchar(200) DEFAULT NULL,
  title VARCHAR (100) DEFAULT NULL,
  intro VARCHAR(255) DEFAULT NULL,
  lyrics text DEFAULT NULL,
  index tinyint(2) DEFAULT NULL,
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4;

CREATE TABLE video (
  id int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  video_file varchar(200) DEFAULT NULL,
  title VARCHAR (100) DEFAULT NULL,
  intro VARCHAR(255) DEFAULT NULL,
  index tinyint(2) DEFAULT NULL,
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4;


CREATE TABLE tour (
  id int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR (100) DEFAULT NULL COMMENT '标题',
  intro VARCHAR(255) DEFAULT NULL COMMENT '简介',
  content text DEFAULT NULL COMMENT '正文',
  index tinyint(2) DEFAULT NULL COMMENT '顺序',
  publish tinyint(2) DEFAULT 0 COMMENT '0 不发布， 1 发布',
  add_time DEFAULT CURRENT_TIMESTAMP COMMENT '发布时间'
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4;
